name: First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        
        steps:
        - name: copy repo
          uses: actions/checkout@v4

        - name: List & Read Files
          run: |
              echo "First Workflow in GitHub Actions"
              ls -ltra
              cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon .txt
