name: First Workflow

on: push

jobs:
    firs_job:
        runs-on: ubuntu-latest
        
        steps:
        - name: Welcome message
          run: echo "First Workflow"
        
        - name: copy repo
          uses: actions/checkout@v4

        - name: List file
          run: ls

        - name: Read file
          run: cat README.md